server:
  host: localhost
  port: 3001
postgresql:
  host: aws-0-ap-southeast-1.pooler.supabase.com
  port: 5432
  username: postgres.tjusoohezjdnjxzxufuy
  password: jnLYJ4ueKiVGi3u7
  database: postgres
security:
  jwt:
    secret: 6f96125a475dbdc4ba4ed2c38ebd93c89f0c633149b7d5cddb2381cbc1398541
